/// <reference path="../../Script/objects/game.ts">
/// <reference path="../../Script/objects/label.ts">
/// <reference path="../../Script/objects/button.ts"
/// <reference path="../../Script/config/scene.ts">>
/// <reference path="../../Script/objects/scene.ts">
/// <reference path="../../Script/objects/gameObject.ts">
/// <reference path="../../Script/objects/player.ts">
/// <reference path="../../Script/objects/enemy.ts">
/// <reference path="../../Script/objects/bullet.ts">
/// <reference path="../../Scripts/scenes/over.js">
/// <reference path="../../Scripts/scenes/play.js">
/// <reference path="../../Scripts/scenes/start.js">
//# sourceMappingURL=_references.js.map